@baseUrl = http://localhost:5149

### Register
POST {{baseUrl}}/api/Auth/register
Content-Type: application/json

{
    "fullName": "Test User",
    "email": "testeri@gmail.com",
    "password": "test123"
}

### Login
POST {{baseUrl}}/api/Auth/login
Content-Type: application/json

{
    "email": "testeeri@gmail.com",
    "password": "test123"
}